[snowflake]
user = "YOUR_USER"
password = "YOUR_PASSWORD"
account = "YOUR_ACCOUNT"          # e.g., wg47389.ap-southeast-1
warehouse = "SNOWFLAKE_LEARNING_WH"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"
