[snowflake]
user = "KartikeyaSharma24"
password = "Sharma@24!!!!!!"
account = "wg47389.ap-southeast-1"          # e.g., wg47389.ap-southeast-1
warehouse = "SNOWFLAKE_LEARNING_WH"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"
